### PR TITLE
fix trailing space

### PR DESCRIPTION
**Pull request by G1K**
sorry forgot to remove from a space. merge again

### CODE REVIEW

**Comment by G1K** [comment]
@junnikokuki pls merge

**Comment by junnikokuki** [comment]
merged but the check failed. How to redo the checks?

**Comment by G1K** [comment]
I checked lint, it went well. But something came out in a third-party file .h it does not seem to apply to the current Pr. Need or ask the project team to disassemble

**Comment by G1K** [comment]
https://github.com/esphome/esphome/pull/677

Neighboring PRS do not pass with the same error.

**Comment by junnikokuki** [comment]
If I revert the merge then merge again, will it be OK?

**Pull request merged**
